name: Verify Expo Starts

on:
  push:        # runs on every push
  pull_request:

jobs:
  expo-start:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install expo-cli globally
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm ci

      - name: Start Expo and verify it boots
        run: |
          cd mobileapp/
          
          # Start Expo in the background, capturing all output
          npx expo start --non-interactive --max-workers 1 &> expo.log &
          PID=$!

          echo "⏳ Waiting for Metro Bundler to be ready..."
          for i in {1..30}; do
            if grep -q "Metro Bundler ready" expo.log; then
              echo "✅ Metro Bundler is up!"
              kill $PID 2>/dev/null || true
              exit 0
            fi
            sleep 1
          done

          echo "❌ Expo did not start within 30 seconds."
          echo "—— expo.log ————"
          tail expo.log
          kill $PID 2>/dev/null || true
          exit 1
