jobs:
  enforce-branch-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Commit Author
        run: echo "COMMITTER=${{ github.actor }}" >> $GITHUB_ENV

      - name: Check if user is an admin
        run: |
          ADMIN_USERS=("neenanhi" "Bonapetite21")  # Add other admins here
          IS_ADMIN=false
          for ADMIN in "${ADMIN_USERS[@]}"; do
            if [ "$COMMITTER" = "$ADMIN" ]; then
              IS_ADMIN=true
              break
            fi
          done

          if [ "$IS_ADMIN" = true ]; then
            echo "User $COMMITTER is an admin. Allowing commit."
          else
            echo "ERROR: Direct commits to main are not allowed for non-admin users."
            exit 1
          fi
