name: Verify Expo Starts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  expo-start:
    runs-on: ubuntu-latest
    env:
      CI: true    # disables prompts in the new Expo CLI

    defaults:
      run:
        working-directory: mobileapp  # point at your Expo project

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3

      - name: Install legacy Expo CLI v5
        run: npm install -g expo-cli@5

      - name: Install project dependencies
        run: npm install

      - name: Start Expo and verify Metro Bundler
        run: |
          # Launch Metro via Expo, capture output
          expo start --tunnel &> expo.log &
          PID=$!

          echo "⏳ Waiting for Metro Bundler to be ready…"
          for i in {1..30}; do
            if grep -q "Metro Bundler ready" expo.log; then
              echo "✅ Metro Bundler is up!"
              kill $PID 2>/dev/null || true
              exit 0
            fi
            sleep 1
          done

          echo "❌ Expo did not start within 30 seconds."
          echo "—— expo.log ————"
          tail expo.log
          kill $PID 2>/dev/null || true
          exit 1
